class PrompterException(Exception):
    ...

class PrompterSectionUpdateException(PrompterException):
    ...

class PromptDataEmpty(PrompterException):
    ...

class PromptDataFileNotFound(PrompterException):
    ...

class PromptDataFilePermissionError(PrompterException):
    ...

class PromptDataFileCorrupted(PrompterException):
    ...

class PromptInconsistentSectionsError(PrompterException):
    ...

class PrompterSectionValueExists(PrompterException):
    ...

class PrompterDeletionArgsError(PrompterException):
    ...

class PrompterSectionDeleteException(PrompterException):
    ...

class PrompterAddError(PrompterException):
    ...

class PrompterSectionAddException(PrompterException):
    ...

class PrompterRestoreOriginalDbNotFound(PrompterException):
    ...

class PrompterRestoreOriginalCopyError(PrompterException):
    ...

class PrompterExitRestore(SystemExit):
    ...
